language: python
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
python:
  - "2.7"
script:
  py.test --cov .
after_success:
  - pip install coveralls
  - coveralls
